namespace:
  name: saa-demo

replicaCount: 3

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

resource:
  requests:
    cpu: 50m
    memory: 256Mi

service:
  port: 8111
  type: LoadBalancer

configmap:
  data: "version: alpine"

