apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-demo.yaml
    path: helm
    repoURL: https://github.com/sakuffo/config-man.git
    targetRevision: HEAD