namespace:
  name: saa-prod

replicaCount: 2

image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent

resource:
  requests:
    cpu: 70m
    memory: 256Mi

service:
  port: 80
  type: LoadBalancer

configmap:
  data: "version: 1.17.0"

